name: Build Package

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v6.0.1

      - name: 🐍 Install uv and set Python version ${{ inputs.python-version }}
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: ${{ inputs.python-version }}
          activate-environment: true

      - name: 🏗️ Build source and wheel distributions
        run: |
          uv pip install -r pyproject.toml --group build
          uv build
          uv run twine check --strict dist/*

      - name: 📤 Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Minimize uv cache
        run: uv cache prune --ci
