name: Docs/Test WorkFlow

on:
  pull_request:
    branches: ["main", "release/*", "develop"]
  push:
    branches: ["main", "release/*", "develop"]
  workflow_dispatch: {}

# Restrict permissions by default
permissions:
  contents: read # Required for checkout
  checks: write # Required for test reporting

jobs:
  docs-build-test:
    name: Test docs build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: 🐍 Install uv and set Python
        uses: astral-sh/setup-uv@v7.2.0
        with:
          python-version: "3.10"
          activate-environment: true

      - name: 🏗️ Install dependencies
        timeout-minutes: 5
        run: uv pip install -e ".[plus]" --group docs

      - name: 🧪 Test Docs Build
        run: uv run mkdocs build --verbose

      - name: Minimize uv cache
        run: uv cache prune --ci
